$akaneDir = ~/.dotfiles/akane
exec = hyprctl dispatch submap global
submap = global

source = hyprland/env.conf
source = hyprland/execs.conf
source = hyprland/general.conf
source = hyprland/rules.conf
source = hyprland/keybinds.conf

source = custom/env.conf
source = custom/execs.conf
source = custom/general.conf
source = custom/rules.conf
source = custom/keybinds.conf

source = workspaces.conf
source = monitors.conf
