general {
    hide_cursor = true
    grace = 2
}

background {
    monitor =
    color = rgba(11131FFF)
}

input-field {
    monitor =
    size = 260, 52
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.25
    outer_color = rgba(8AB4F8FF)
    inner_color = rgba(1A2132CC)
    font_color = rgba(EDF4FFFF)
    fade_on_empty = true
    placeholder_text = Password...
    position = 0, -40
    halign = center
    valign = center
}

label {
    monitor =
    text = $TIME
    color = rgba(EDF4FFFF)
    font_size = 64
    font_family = Inter Tight
    position = 0, 220
    halign = center
    valign = center
}

label {
    monitor =
    text = $USER
    color = rgba(EDF4FFCC)
    font_size = 20
    font_family = Inter Tight
    position = 0, 40
    halign = center
    valign = center
}
