windowrule = suppress_event maximize, match:class .*
windowrule = float on, match:class ^(pavucontrol)$
windowrule = center on, match:class ^(pavucontrol)$
windowrule = size 50% 60%, match:class ^(pavucontrol)$
windowrule = float on, match:title ^(Open File|Save As|Choose wallpaper|File Upload)(.*)$
windowrule = center on, match:title ^(Open File|Save As|Choose wallpaper|File Upload)(.*)$
windowrule = no_shadow on, match:float false

workspace = special:special, gapsout:24

layerrule = blur on, match:namespace quickshell:.*
layerrule = ignore_alpha 0.78, match:namespace quickshell:.*
layerrule = blur on, match:namespace gtk-layer-shell
layerrule = ignore_alpha 0.0, match:namespace gtk-layer-shell
